ta_web/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(
        r'^$',
        views.homepage,
        name='homepage'
    ),

    # Document URLs

    url(
        r'^document/all$',
        views.show_entries,
        name='show_entries'
    ),

    url(
        r'^document/(?P<pk>\d+)$',
        views.entry_detail,
        name='entry_detail'
    ),

    url(
        r'^document/add/$',
        views.add_document,
        name='add_document'
    ),

    url(
        r'^register/$',
        views.register,
        name='register'
    ),

    url(
        r'^logout_message/$',
        views.logout_message,
        name='logout_message'
    ),

]

text_analysis/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from ta_web import views

urlpatterns = [
    #####################################
    # ADMIN CONSOLE
    #####################################
    url(
        r'^admin/',
        admin.site.urls
    ),
    #####################################
    # ta_web
    #####################################
    # route to ta_web
    url(
        r'^',
        include(
            'ta_web.urls',
            namespace='ta_web'
        )
    ),
    # login
    url(
        r'^accounts/login/',
        auth_views.login,
        name='login'
    ),
    # logout
    url(
        r'^accounts/logout/$',
        auth_views.logout,
        name='logout'
    ),
    # register
    url(
        r'^register/$',
        views.register,
        name='register'
    ),
]

ta_web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# import datetime
from . import eq
from .calc import analyze_string

User._meta.get_field('email')._blank = False  # TODO email validator


class Profile(models.Model):

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='profile')
    signup_date = models.DateTimeField()
    description = models.CharField(max_length=200, blank=True, null=True)
    website_url = models.CharField(
        max_length=200, null=True)  # TODO url validator

    def __str__(self):
        return '{}, {}'.format(self.user.username, self.signup_date)


class Document(models.Model):
    title = models.CharField(max_length=200)
    date_submitted = models.DateTimeField(blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    sentences = models.IntegerField(blank=True, null=True)
    words = models.IntegerField(blank=True, null=True)
    syllables = models.IntegerField(blank=True, null=True)
    characters = models.IntegerField(blank=True, null=True)
    polysyllables = models.IntegerField(blank=True, null=True)
    readability_index = models.FloatField(blank=True, null=True)
    fk_grade_level = models.FloatField(blank=True, null=True)
    ari = models.FloatField(blank=True, null=True)
    smog = models.FloatField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def submit(self):
        """
            Process submitted text.
        """
        self.date_submitted = timezone.now() # django utils
        # self.date_submitted = datetime.datetime.now()

        self.sentences, self.words, self.syllables, \
            self.characters, self.poly_syllables = analyze_string(
                self.text)

        self.readability_index = eq.fk_re(
            self.words, self.sentences, self.syllables)
        self.fk_grade_level = eq.fk_gl(
            self.words, self.sentences, self.syllables)
        self.ari = eq.ari(self.words, self.sentences, self.characters)
        self.smog = eq.smog(self.poly_syllables)

    def __str__(self):
        return '{}, {}'.format(self.title, self.date_submitted)

ta_web/forms.py
from django import forms
from .models import Document, Profile

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.forms import ValidationError

BLANK_FIELD = "Field cannot be blank."
DUPLICATE = "%s taken."


class AddDocumentForm(forms.ModelForm):

    class Meta:

        model = Document
        fields = ('title', 'text',)

    # ########################################
    # # The following MAY be used eventually
    # # ... figured that they should be included
    # #
    # def clean_title(self):
    #
    #     title = self.cleaned_data['title']
    #
    #     if not title:
    #         ValidationError(BLANK_FIELD)
    #
    #     return title
    #
    # def clean_text(self):
    #
    #     text = self.cleaned_data['text']
    #
    #     if not text:
    #         ValidationError(BLANK_FIELD)
    #
    #     return text
    #
    # def save(self, commit=True):
    #
    #     document = super(AddDocumentForm, self).save(commit=False)
    #     document.title = self.cleaned_data['title']
    #     document.text = self.cleaned_data['text']
    #
    #     if commit:
    #         # document.submit()
    #         document.save()
    #
    #     return document()
    # #
    # ########################################


class CreateUserForm(UserCreationForm):

    class Meta:

        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2')

    def clean_username(self):

        field = 'Username'

        username = self.cleaned_data['username']

        if not username:
            raise ValidationError(DUPLICATE % field)

        if User.objects.filter(username__icontains=username).exists():
            raise ValidationError('Username taken!')

        return username

    def clean_first_name(self):

        first_name = self.cleaned_data['first_name']

        if not first_name:
            raise ValidationError(BLANK_FIELD)

        return first_name

    def clean_last_name(self):

        last_name = self.cleaned_data['last_name']

        if not last_name:
            raise ValidationError(BLANK_FIELD)

        return last_name

    def clean_email(self):

        field = 'Email'

        email = self.cleaned_data['email']

        if not email:
            raise ValidationError(BLANK_FIELD)

        if User.objects.filter(email__iexact=email).exists():
            ValidationError(DUPLICATE % field)

        return email

    def save(self, commit=True):

        user = super(CreateUserForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()

        return user


class UserProfileForm(forms.ModelForm):

    """...included in case social functionality will be included (eventually)"""

    class Meta:
        model = Profile
        fields = ['description', 'website_url']


ta_web/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import Http404
from .models import Document, Profile
from .forms import CreateUserForm, AddDocumentForm


def homepage(request):
    return render(request, 'ta_web/home.html')


@login_required
def show_entries(request):

    documents = Document.objects.all().filter(
        user=request.user
    ).order_by(
        'date_submitted'
    )

    return render(request, 'ta_web/show_documents.html', {'documents': documents})


@login_required
def entry_detail(request, pk):

    # try:
    #     document = Document.objects.get(pk=pk)
    # except Document.DoesNotExist:
    #     raise Http404('Document DOES NOT EXIST')

    document = get_object_or_404(Document, pk=pk)

    return render(request, 'ta_web/document_detail.html', {'document': document})


def add_document(request):

    if request.method == 'POST':

        form = AddDocumentForm(request.POST)

        if form.is_valid():

            data = form.cleaned_data
            doc = Document.objects.create()
            doc.user = request.user
            doc.title = data['title']
            doc.text = data['text']
            doc.submit()
            doc.save()

            return redirect('ta_web:entry_detail', pk=doc.pk)

    else:

        form = AddDocumentForm()

    return render(request, 'ta_web/add_document.html', {'form': form})


##################################################################
#
# User views...
#
# - user registration
# - logout redirect
#
##################################################################

def register(request):

    if request.method == 'POST':

        form = CreateUserForm(request.POST)

        if form.is_valid():

            user = form.save()
            user = authenticate(
                username=request.POST['username'],
                password=request.POST['password1']
            )
            login(request, user)

            return redirect('ta_web:homepage')

        else:

            return render(request, 'registration/register.html', {'form': form})

    else:

        form = CreateUserForm()

        return render(request, 'registration/register.html', {'form': form})


def logout_message(request):

    return render(request, 'ta_web/logout_message.html')

ta_web/templates/ta_web/add_document.html
{% extends 'ta_web/base.html' %}
{% block content %}
<div class="col-sm-12">
    <h3>Add a Document</h3><hr>
    <form method="post" action="">{% csrf_token %}
        <table id="add_document_form">
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>

{% endblock %}

ta_web/templates/ta_web/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Text Analysis Advanced</title>
  <!--- BOOTSTRAPPE --->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!--- STATIC FILES --->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="{% static 'javascript/scripts.js' %}"></script>

</head>

<body>

  <div class="container">
    <div class="page-header">
      <h1><a href="/">Text Analysis Advanced</a></h1>
    </div>
    <div class="user_login">
      {% if user.is_authenticated %}
      <a href="{%  url 'ta_web:add_document' %}">Add a document.</a> || <a href="{% url 'ta_web:show_entries' %}">Your Documents</a> || <a href="{% url 'logout' %}?next={% url 'ta_web:logout_message' %}">Log Out</a>
      {% else %}
      <a href="{% url 'login' %}?next= {{ request.path }}">Log in/sign up</a> {% endif %}
    </div>
    <div class="row">
      <!--- various views rendered here --->
      {% block content %} {% endblock %}
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="byline">
        © 2017 ranesi | <a href="https://github.com/ranesi">GitHub</a> | <a href="mailto:ranesi@acm.org">email</a>
      </div>
    </div>
  </div>

</body>

</html>

ta_web/templates/ta_web/document_detail.html
{% extends 'ta_web/base.html' %}
{% block content %}
  <div class="document" style="margin:30px;color:#000;background-color:#f8f8f8;border:3px solid #444; border-radius:5px; padding: 30px">
    {% if document.date_submitted %}
      <div class="date">
        {{ document.date_submitted }}
      </div>
    {% endif %}
    <h3>{{ document.title }}</h3>
    <pre>
        Sentences.......{{ document.sentences }}
        Words...........{{ document.words }}
        Syllables.......{{ document.syllables }}
        <!---Polysyllables...{{ document.polysyllables }}--->
      </pre>
  <h3>Indices</h3>
      <pre>
        Readability.....{{ document.readability_index }}
        Grade Level.....{{ document.fk_grade_level }}
        ARI.............{{ document.ari }}
    </pre>
      <a href="{% url 'ta_web:show_entries' %}"><h3>Back</h3></a>
  <hr>
  </div>
{% endblock %}

ta_web/templates/ta_web/home.html
{% extends 'ta_web/base.html' %}
{% block content %}
    <div class="col-sm-12">
        <h3>Welcome to TAA (text analysis something)</h3>
        {% if user.is_authenticated %}
            <p><a href="{%  url 'ta_web:add_document' %}">Add a document.</a></p>
        {% else %}
            <p>To analyze a document, please login or create an account.</p>
        {% endif %}
    </div>
{% endblock %}

ta_web/templates/ta_web/logout_message.html
{% extends 'ta_web/base.html' %} {% block content %}
<div class="col-sm-12">
  <h3>Logged out successfully.</h3>
  <a href="{% url 'ta_web:homepage' %}">Return</a>
</div>
{% endblock %}

ta_web/templates/ta_web/show_documents.html
{% extends 'ta_web/base.html' %}

{% block content %}
<div class="col-sm-12">
{% for doc in documents %}

<div class="documents" style="margin: 30px;color: #000; background-color: #f8f8f8; border: 3px solid #444; border-radius: 5px; padding: 30px">
    <h3><a href="{% url 'ta_web:entry_detail' pk=doc.pk %}">{{ doc.title }}</a></h3>
    <div class="date"><p>{{ doc.date_submitted }}</p></div>
    </div>
    {% empty %}
    <p>No documents yet submitted!</p>

{% endfor %}
    </div>
{% endblock %}